# Generated by Django 3.2.3 on 2021-06-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseBiochimie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseHémobiologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseMicrobiologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseParasitologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomService', models.CharField(max_length=200, null=True)),
                ('responsable', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telService', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPatient', models.CharField(max_length=200)),
                ('prenomPatient', models.CharField(max_length=200)),
                ('idPatient', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('service', models.CharField(max_length=200)),
                ('Nommedecin_demandeur', models.CharField(max_length=200)),
                ('Prenommedecin_demandeur', models.CharField(max_length=200)),
                ('date_ajout_demande', models.DateTimeField(auto_now_add=True)),
                ('nb_prelevement', models.PositiveIntegerField()),
                ('nature_prelevement', models.CharField(max_length=200)),
                ('type_tube', models.CharField(max_length=200)),
                ('Biochimie', models.ManyToManyField(to='Analyse.AnalyseBiochimie')),
                ('Hémobiologie', models.ManyToManyField(to='Analyse.AnalyseHémobiologie')),
                ('Microbiologie', models.ManyToManyField(to='Analyse.AnalyseMicrobiologie')),
                ('Parasitologie', models.ManyToManyField(to='Analyse.AnalyseParasitologie')),
            ],
        ),
    ]
