from django.urls import path, include
from . import views

urlpatterns = [
    path('Resultats/', views.Resultats, name="Resultats"),
    path('ResultatUniteBiochimie/', views.ResultatUniteBiochimie, name='ResultatUniteBiochimie'),
    path('ResultatUniteParasitologie/', views.ResultatUniteParasitologie, name='ResultatUniteParasitologie'),
    path('ResultatUnitéMicrobiologie/', views.ResultatUnitéMicrobiologie, name='ResultatUnitéMicrobiologie'),
    path('ResultatUniteHémobiologie/', views.ResultatUniteHémobiologie, name='ResultatUniteHémobiologie'),
    path('voirResultats/', views.Resultats, name='voirResultats'),

    path('chercherDemande/', views.listeDemandeCopro, name='listeDemandeCopro'),
    path('ajouter-Coproparasitologies/<str:pk>', views.ajouterResultat_coproparasitologie, name='coproparasitologie'),
    path('ResultatCoproParasitologie/', views.voirCoproparasitologie, name='listeCopro'),
    path('SupprimerCoproParasitologie/<str:pk>', views.supprimerResultatCoproparasitologie, name='supprimerCopro'),
    path('modifierCoproParasitologie/<str:pk>', views.modifierResultatCopro, name='modifierCopro'),
    path('EnvoyerResultatCopro/<str:pk>', views.EnvoyerResultatCopro, name='EnvoyerResultatCopro'),
    path('AfficherResultatCopro/<str:pk>', views.AfficherResultatCopro, name='AfficherResultatCopro'),

    path('ajouter-Bactériologie/<str:pk>', views.ajouterResultat_bacteriologie, name='bacteriologie'),
    path('chercherDemandeBacterio/', views.listeDemandeBactériologie, name='listeDemandeBacterio'),
    path('ResultatBactériologie/', views.voirBactériologie, name='listeBacterio'),
    path('SupprimerBactériologie/<str:pk>', views.supprimerResultatBactériologie, name='supprimerBactériologie'),
    path('EnvoyerResultatBacterio/<str:pk>', views.EnvoyerResultatBacterio, name='EnvoyerResultatBacterio'),
    path('AfficherResultatBacterio/<str:pk>', views.AfficherResultatBacterio, name='AfficherResultatBacterio'),

    path('ajouter-Entérocoque/<str:pk>', views.ajouterResultat_Entérocoque, name='Entérocoque'),
    path('chercherDemandeEntérocoque/', views.listeDemandeEntérocoque, name='listeDemandeEntérocoque'),
    path('ResultatEntérocoque/', views.voirEntérocoque, name='listeEntérocoque'),
    path('SupprimerEntérocoque/<str:pk>', views.supprimerResultatEntérocoque, name='supprimerEntérocoque'),
    path('modifierEntérocoque/<str:pk>', views.modifierResultatEntérocoque, name='modifierEntérocoque'),
    path('EnvoyerResultatEntérocoque/<str:pk>', views.EnvoyerResultatEntérocoque, name='EnvoyerResultatEntérocoque'),
    path('AfficherResultatEntérocoque/<str:pk>', views.AfficherResultatEntérocoque, name='AfficherResultatEntérocoque'),

    path('chercherDemandeGroupageSanguin/', views.listeDemandeGroupageSanguin, name='listeDemandeGroupageSanguin'),
    path('ajouter-GroupageSanguin/<str:pk>', views.ajouterResultat_GroupageSanguin, name='GroupageSanguin'),
    path('ResultatGroupageSanguin/', views.voirGroupageSanguin, name='listeGroupageSanguin'),
    path('SupprimerGroupageSanguin/<str:pk>', views.supprimerResultatGroupageSanguin, name='supprimerGroupageSanguin'),
    path('EnvoyerResultatGroupeSanguin/<str:pk>', views.EnvoyerResultatGroupeSanguin,
         name='EnvoyerResultatGroupeSanguin'),
    path('AfficherResultatGroupeSanguin/<str:pk>', views.AfficherResultatGroupeSanguin,
         name='AfficherResultatGroupeSanguin'),

    path('chercherDemandeFNS/', views.listeDemandeFNS, name='listeDemandeFNS'),
    path('ajouter-FNS/<str:pk>', views.ajouterResultat_FNS, name='FNS'),
    path('ResultatFNS/', views.voirFNS, name='listeFNS'),
    path('SupprimerFNS/<str:pk>', views.supprimerResultatFNS, name='supprimerFNS'),
    path('modifierFNS/<str:pk>', views.modifierResultatFNS, name='modifierFNS'),
    path('SupprimerFNS/<str:pk>', views.supprimerResultatFNS, name='supprimerFNS'),
    path('modifierFNS/<str:pk>', views.modifierResultatFNS, name='modifierFNS'),
    path('AfficherResultatFNS/<str:pk>', views.AfficherResultatFNS, name='AfficherResultatFNS'),
    path('EnvoyerResultatFNS/<str:pk>', views.EnvoyerResultatFNS, name='EnvoyerResultatFNS'),

    path('chercherDemandePseudomonas/', views.listeDemandePseudomonas, name='listeDemandePseudomonas'),
    path('ajouter-Pseudomonas/<str:pk>', views.ajouterResultat_Pseudomonas, name='Pseudomonas'),
    path('ResultatPseudomonas/', views.voirPseudomonas, name='listePseudomonas'),
    path('AfficherResultatPseudomonas/<str:pk>', views.AfficherResultatPseudomonas, name='AfficherResultatPseudomonas'),
    path('EnvoyerResultatPseudomonas/<str:pk>', views.EnvoyerResultatPseudomonas, name='EnvoyerResultatPseudomonas'),
    path('modifierPseudomonas/<str:pk>', views.modifierResultatPseudomonas, name='modifierPseudo'),

    path('chercherDemandeEntérobactéries/', views.listeDemandeEntérobactéries, name='listeDemandeEntérobactéries'),
    path('ajouter-Entérobactéries/<str:pk>', views.ajouterResultat_Entérobactéries, name='Entérobactéries'),
    path('ResultatEntérobactéries/', views.voirEntérobactéries, name='listeEntérobactéries'),
    path('SupprimerEntérobactéries/<str:pk>', views.supprimerResultatEntérobactéries, name='supprimerEntérobactéries'),
    path('modifierEntérobactéries/<str:pk>', views.modifierResultatEntérobactéries, name='modifierEntérobactéries'),
    path('AfficherResultatEntérobactéries/<str:pk>', views.AfficherResultatEntérobactéries,
         name='AfficherResultatEntérobactéries'),
    path('EnvoyerResultatEntérobactéries/<str:pk>', views.EnvoyerResultatEntérobactéries,
         name='EnvoyerResultatEntérobactéries'),

    path('chercherDemandeStapylocoque/', views.listeDemandeStapylocoque, name='listeDemandeStapylocoque'),
    path('ajouter-Stapylocoque/<str:pk>', views.ajouterResultat_Stapylocoque, name='Stapylocoque'),
    path('ResultatStapylocoque/', views.voirStapylocoque, name='listeStapylocoque'),
    path('SupprimerStapylocoque/<str:pk>', views.supprimerResultatStapylocoque, name='supprimerStapylocoque'),
    path('modifierStapylocoque/<str:pk>', views.modifierResultatStapylocoque, name='modifierStapylo'),
    path('AfficherResultatStapylocoque/<str:pk>', views.AfficherResultatStapylocoque,
         name='AfficherResultatStapylocoque'),
    path('EnvoyerResultatStapylocoque/<str:pk>', views.EnvoyerResultatStapylocoque,
         name='EnvoyerResultatStapylocoque'),

    path('chercherDemandeAcinetobacter/', views.listeDemandeAcinetobacter, name='listeDemandeAcinetobacter'),
    path('ajouter-Acinetobacter/<str:pk>', views.ajouterResultat_Acinetobacter, name='Acinetobacter'),
    path('ResultatAcinetobacter/', views.voirAcinetobacter, name='listeAcinetobacter'),
    path('SupprimerAcinetobacter/<str:pk>', views.supprimerResultatAcinetobacter, name='supprimerAcinetobacter'),

    path('chercherDemandeBiochimieGenerale/', views.listeDemandeBiochimieGénérale,
         name='listeDemandeBiochimieGénérale'),
    path('ajouter-BiochimieGenerale/<str:pk>', views.ajouterResultat_BiochimieGénérale, name='BiochimieGénérale'),
    path('ResultatBiochimieGenerale/', views.voirBiochimieGénérale, name='listeBiochimieGénérale'),
    path('SupprimerBiochimieGenerale/<str:pk>', views.supprimerResultatBiochimieGénérale,
         name='supprimerBiochimieGenerale'),
    path('AfficherResultatBiochimieGenerale/<str:pk>', views.AfficherResultatBiochimieGenerale,
         name='AfficherResultatBiochimieGenerale'),
    path('EnvoyerResultatBiochimieGenerale/<str:pk>', views.EnvoyerResultatBiochimieGenerale,
         name='EnvoyerResultatBiochimieGenerale'),

    path('chercherDemandeBilanDurgence/', views.listeDemandeBilanDurgence, name='listeDemandeBilanDurgence'),
    path('ajouter-BilanDurgence/<str:pk>', views.ajouterResultat_BilanDurgence, name='BilanDurgence'),
    path('ResultatBilanDurgence/', views.voirBilanDurgence, name='listeBilanDurgence'),
    path('SupprimerBilanDurgence/<str:pk>', views.supprimerResultatBilanDurgence, name='supprimerBilanDurgence'),
    path('modifierBilanDurgence/<str:pk>', views.modifierResultatBilanDurgence, name='modifierBilan'),

    path('listeDemander/<str:pk>', views.listeAnalyse, name='listeAnalyseDemander'),
    path('consulterResultat/<str:pk>', views.consulterResultat, name='consulterResultat'),
    path('ResultatCopro/<str:pk>', views.voirResultatCoproparasitologie, name='ResultatCopro'),
    path('ResultatEntérocoque/<str:pk>', views.voirResultatEntérocoque, name='ResultatEntérocoque'),
    path('Resultatbactériologie/<str:pk>', views.voirResultatbactériologie, name='Resultatbactériologie'),
    path('modifierbactériologie/<str:pk>', views.modifierResultatBactériologie, name='modifierbactériologie'),

    path('ResultatStapylocoque/<str:pk>', views.voirResultatStapylocoque, name='ResultatStapylocoque'),
    path('ResultatEntérobactéries/<str:pk>', views.voirResultatEntérobactéries, name='ResultatEntérobactéries'),
    path('ResultatPseudomonas/<str:pk>', views.voirResultatPseudomonas, name='ResultatPseudomonas'),
    path('ResultatAcinetobacter/<str:pk>', views.voirResultatAcinetobacter, name='ResultatAcinetobacter'),
    path('modifierAcinetobacter/<str:pk>', views.modifierResultatAcinetobacter, name='modifierAcineto'),

    path('ResultatFNS/<str:pk>', views.voirResultatFNS, name='ResultatFNS'),
    path('ResultatGroupageSanguin/<str:pk>', views.voirResultatGroupageSanguin, name='ResultatGroupageSanguin'),
    path('modifierGroupageSanguin/<str:pk>', views.modifierResultatGroupageSanguin, name='modifierGroupe'),

    path('ResultatBilanDurgence/<str:pk>', views.voirResultatBilanDurgence, name='ResultatBilanDurgence'),
    path('ResultatBiochimieGénérale/<str:pk>', views.voirResultatBiochimieGénérale, name='ResultatBiochimieGénérale'),
    path('modifierBiochimieGénérale/<str:pk>', views.modifierResultatBiochimieGénérale, name='modifierBioc'),

    path('AfficherResultatBilanDurgence/<str:pk>', views.AfficherResultatBilanDurgence,
         name='AfficherResultatBilanDurgence'),
    path('EnvoyerResultatBilanDurgence/<str:pk>', views.EnvoyerResultatBilanDurgence,
         name='EnvoyerResultatBilanDurgence'),

]
