# Generated by Django 3.2.3 on 2021-06-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('nbrPatient', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Service Patient nbr',
            },
        ),
    ]
