# Generated by Django 3.2.5 on 2021-07-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Statistique', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePatient',
        ),
    ]
